Added the full functionality of the recipe application
hiromataba/Recipe-app pull request #13
Opened 2021-11-18 19:49 UTC by moise10r

### In this project, we did the following tasks:
 
- You should follow the layout of the wireframes provided. You should personalize the rest of the design including colours, typographies, spacings, etc.
- Login page and registration page:
    - Should be built with Devise.
- Food list:
    - Should display a list of food as in the wireframe.
    - Should lead to the form that allows users to add new food.
- Recipes list:
    - Should display a list of recipes created by the logged-in user as in the wireframe.
    - Should lead to recipe details.
    - If the user is the owner of the recipe, should allow user to delete it.
- Public recipe list:
    - Should display a list of all public recipes ordered by newest as in the wireframe.
    - Should lead to recipe details.
- Recipe details:
    - If the recipe is public or the user is the owner of the recipe, should display the recipe details as in the wireframe.
    - If the user is the owner of the recipe, should lead to the form that allows user to add new food.
- General shopping list view (**do not implement if in group of 3**):
    - Should show the list of food that is missing for all recipes of the logged-in user.
    - Should count the total food items and total price of the missing food.
- Make sure there are no N+1 queries happening.
- Create navigation menu that allows users to open all of the pages you created.

2021-11-18 21:59 UTC, sinansevgi requested changes
# Changes Required :recycle: 
------

Hi @moise10r and @hiromataba , 

Good job so far!
Kudos for implementing the inventory feature too :clap: 
There are some issues that you still need to work on to go further but you are almost there!



 ## Required Changes ♻️

- [x] You should make **integration tests** with the capybara gem to test your application.  

_Please check the inline comments for my suggestions_ :arrow_down:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi

------

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-18 21:59 UTC, sinansevgi commented on app/controllers/recipes_controller.rb
> +  end
- [ ] You should avoid making SQL queries from the controller. Your controllers should only redirect data that they get from models. You should always make SQL queries from the model.

2021-11-18 21:59 UTC, sinansevgi commented on app/controllers/users_controller.rb
> +  end
- [ ] You should avoid making SQL queries from the controller. Your controllers should only redirect data that they get from models. You should always make SQL queries from the model.  
The controllers should be concerned with HTTP verbs. (thin controller rule) By that, I mean that a controller’s responsibility should be focused on web requests. Other operations should be handled on the model.

2021-11-18 21:59 UTC, sinansevgi commented on app/views/foods/index.html.erb
> +        </tr>
[Optional]
- [ ] It will be really great if you use `partials` for rendering a collection of elements.

2021-11-18 21:59 UTC, sinansevgi commented on app/controllers/inventories_controller.rb
> +  end
- [ ] The controllers should be concerned with HTTP verbs. (thin controller rule) By that, I mean that a controller’s responsibility should be focused on web requests. Other calculations should be handled on the model.

2021-11-18 21:59 UTC, sinansevgi commented on app/controllers/inventories_controller.rb
> +      difference = inventory_food.quantity - recipe_food.quantity
- [ ] When I try to generate a shopping list, the application crashes. if I don't have a food item in my inventory. 

![Screenshot 2021-11-19 at 00-45-10 Action Controller Exception caught](https://user-images.githubusercontent.com/1642014/142502460-48d524ae-68d0-4af7-b293-a3c8694edf3d.png)

2021-11-19 12:24 UTC, Emmyn5600 approved these changes
Hi @moise10r and @hiromataba 

- I liked the design and implementation
- You have clean code 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! :tada:

 #### Optional suggestions
 
 - Read this [article](https://www.toptal.com/ruby-on-rails/top-10-mistakes-that-rails-programmers-make), Which will show you The 10 Most Common Mistakes That Rails Developers Make.
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-11-19 12:26 UTC, hiromataba commented
Thanks a lot for the optional suggestion :pray:

2021-11-19 12:26 UTC, merged